### ISSUE TITLE
Cara Install ? 

### ISSUE THREAD

**Issue by jufianto** [null-id/mongotest#1]
kalau bisa jelasin cara nginstallnya gimana om :D

**Comment by vck** [comment]
@JufiantoHenri  
- install mongodb
- npm install
- node app.js

buka mongodb
- mongo

> use mydb;
> 
> db.users.find()

**Comment by vck** [comment]
https://github.com/null-id/mongotest/commit/1e091732d757e0f21c4b38f16efd57f930db9b78 disini udah ane update README.md nya
